### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by junliu-cn** [tunaemre/Face-Swap-Android#4]
Hi,
I'm using your code for face swap on android,but I got many errors when I tring to build the code using android studio.Can you help me with this problem ?Any suggestions will be appreciated.The error information is as follows:
D:\Proj\Android_Proj\Face-Swap-Android1\faceSwap\build\intermediates\res\merged\debug\values-v19\values-v19.xml
Error:(4, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(5, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(11, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(12, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(4, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(5, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(11, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(12, 21) No resource found that matches the given name: attr 'windowNoTitle'.
D:\Proj\Android_Proj\Face-Swap-Android1\faceSwap\build\intermediates\res\merged\debug\values-v21\values-v21.xml
Error:(12, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(13, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(21, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(22, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
Error:(6, 21) No resource found that matches the given name: attr 'colorAccent'.
Error:(4, 21) No resource found that matches the given name: attr 'colorPrimary'.
Error:(5, 21) No resource found that matches the given name: attr 'colorPrimaryDark'.
Error:(12, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(13, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(21, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(22, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
Error:(6, 21) No resource found that matches the given name: attr 'colorAccent'.
Error:(4, 21) No resource found that matches the given name: attr 'colorPrimary'.
Error:(5, 21) No resource found that matches the given name: attr 'colorPrimaryDark'.
D:\Proj\Android_Proj\Face-Swap-Android1\faceSwap\build\intermediates\res\merged\debug\values\values.xml
Error:(40, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(41, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(45, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(46, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(22) Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
Error:(25, 21) No resource found that matches the given name: attr 'colorAccent'.
Error:(23, 21) No resource found that matches the given name: attr 'colorPrimary'.
Error:(24, 21) No resource found that matches the given name: attr 'colorPrimaryDark'.
Error:(27) Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button.Colored'.
Error:(28, 21) No resource found that matches the given name: attr 'colorButtonNormal'.
Error:(31) Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button.Colored'.
Error:(32, 21) No resource found that matches the given name: attr 'colorButtonNormal'.
Error:(35) Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button.Colored'.
Error:(36, 21) No resource found that matches the given name: attr 'colorButtonNormal'.
Error:(40, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(41, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(45, 21) No resource found that matches the given name: attr 'windowActionBar'.
Error:(46, 21) No resource found that matches the given name: attr 'windowNoTitle'.
Error:(22) Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
Error:(25, 21) No resource found that matches the given name: attr 'colorAccent'.
Error:(23, 21) No resource found that matches the given name: attr 'colorPrimary'.
Error:(24, 21) No resource found that matches the given name: attr 'colorPrimaryDark'.
Error:(27) Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button.Colored'.
Error:(28, 21) No resource found that matches the given name: attr 'colorButtonNormal'.
Error:(31) Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button.Colored'.
Error:(32, 21) No resource found that matches the given name: attr 'colorButtonNormal'.
Error:(35) Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Button.Colored'.
Error:(36, 21) No resource found that matches the given name: attr 'colorButtonNormal'.
Error:Execution failed for task ':faceSwap:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by tunaemre** [comment]
Hi there,
Too many errors you had but all of them caused by theme which defined in "style.xml" . Try to redefine all of values and compile project via Android 6.0 (Not supported 7.0 yet).
I'll commit an Android Studio version soon.

**Comment by junliu-cn** [comment]
Sorry,I'm not familiar with android.I don't know how to change the sample code.I tried to learn android NDK by your code.Could you explain it clearly by giving some examples?Thanks.

**Comment by swiftlancer** [comment]
I have many problems in Android Studio, waitting for your  Android Studio version.Thanks.
