### ISSUE TITLE
Compile Issue 

### ISSUE THREAD

**Issue by SHUJAAT-DEV** [tunaemre/Face-Swap-Android#7]
Hi,
 I have download the  repository and import the project into android studio. i have facing different issue related to ndk and openCV . I have copy past all the issue bellow not.

Kindly help me out from this issue.

Thanks

Note Error:-
  Gradle build:
  **Error:A problem occurred configuring project ':faceSwap'.
> executing external native build for ndkBuild C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk**

.........................................Gradle Sync......................

### _Build command failed.
Error while executing 'C:\Users\hp\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=1 APP_PLATFORM=android-17 NDK_OUT=C:/Users/Public/working/Face-Swap-Android-master/faceSwap/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.    
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries    
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.    
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries    
Android NDK: WARNING:C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk:detectionbasedtracker: non-system libraries in linker flags: -lopencv_java3    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk:faceswapper: non-system libraries in linker flags: -lopencv_java3    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
md "C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib\armeabi" >NUL 2>NUL || rem
C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi] "Gdbserver      ": "[arm-linux-androideabi] C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib/armeabi/gdbserver"
copy /b/y "C:\Users\hp\AppData\Local\Android\sdk\ndk-bundle\build\\..\prebuilt\android-arm\gdbserver\gdbserver" "C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib\armeabi\gdbserver" > NUL
C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe [armeabi] "Gdbsetup       ": "C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib/armeabi/gdb.setup"
C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "set solib-search-path C:/Users/Public/working/Face-Swap-Android-master/faceSwap/build/intermediates/ndkBuild/debug/obj/local/armeabi" > C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib/armeabi/gdb.setup
C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../prebuilt/windows-x86_64/bin/echo.exe "directory C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../sysroot "C:/Users/Public/working/opencv-3.3.1-android-sdk/OpenCV-android-sdk/sdk/native/jni/include/opencv" "C:/Users/Public/working/opencv-3.3.1-android-sdk/OpenCV-android-sdk/sdk/native/jni/include" C:/Users/Public/working/Face-Swap-Android-master/faceSwap/src/main/jni C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/include C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include C:/Users/hp/AppData/Local/Android/sdk/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/include/backward" >> C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\debug\lib/armeabi/gdb.setup
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Face-S~1/faceSwap/src/main/jni/DetectionBasedTracker.cpp', needed by `C:/Users/Public/working/Face-Swap-Android-master/faceSwap/build/intermediates/ndkBuild/debug/obj/local/armeabi/objs-debug/detectionbasedtracker/C_/Face-S~1/faceSwap/src/main/jni/DetectionBasedTracker.o'.  Stop.
Build command failed.
Error while executing 'C:\Users\hp\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=0 APP_PLATFORM=android-17 NDK_OUT=C:/Users/Public/working/Face-Swap-Android-master/faceSwap/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\Users\Public\working\Face-Swap-Android-master\faceSwap\build\intermediates\ndkBuild\release\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.    
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries    
Android NDK: OpenCV: You should ignore warning about 'non-system libraries in linker flags' and 'opencv_java' library.    
Android NDK:         'OPENCV_INSTALL_MODULES:=on' can be used to build APK with included OpenCV binaries    
Android NDK: WARNING:C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk:detectionbasedtracker: non-system libraries in linker flags: -lopencv_java3    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
Android NDK: WARNING:C:\Users\Public\working\Face-Swap-Android-master\faceSwap\src\main\jni\Android.mk:faceswapper: non-system libraries in linker flags: -lopencv_java3    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Face-S~1/faceSwap/src/main/jni/DetectionBasedTracker.cpp', needed by `C:/Users/Public/working/Face-Swap-Android-master/faceSwap/build/intermediates/ndkBuild/release/obj/local/armeabi/objs/detectionbasedtracker/C_/Face-S~1/faceSwap/src/main/jni/DetectionBasedTracker.o'.  Stop._

**Comment by tunaemre** [comment]
Hi there,
It seems like Android NDK not properly installed.
You may reinstall than try to recompile repository.
